name: Deploy CV to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: ./.github/actions/checkout

    - name: Set up Node.js
      uses: ./.github/actions/setup-node
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: ./.github/actions/gh-pages
      with:
        publish_dir: ./dist
        user_name: ${{ secrets.GITHUB_ACTOR }}
        user_email: ${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
